apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudnative-pg-install
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.22.2/releases/cnpg-1.22.2.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
